### ISSUE TITLE
Support changing of the working directory for the node process

### ISSUE THREAD

**Issue by eploko** [carouselapps/prerenderer#11]
I’ve got the following edn in my `server-side.cljs.edn`:

```
{:require  [myapp.core]
 :init-fns [myapp.core/main]
 :optimizations :none
 :compiler-options {:target :nodejs
                    :pretty-print true}}
```

It compiles fine with boot-cljs and there’s the `server-side.js` file and the corresponding `server-side.out` folder inside the `target` folder. The issue I’ve got is when I try to run this with node, it bails out with:

> Error: Cannot find module ‘~/projects/myapp/server-side.out/goog/bootstrap/nodejs.js’

It looks like it skips the `target` folder while trying to locate the module.

The resulting `server-side.js` file has this inside:

> require(path.join(path.resolve("."),"server-side.out","goog","bootstrap","nodejs.js"));

Which, as far as I understand, should be resolved properly, but… the devil is in the fact it doesn’t.

I’ve tried to set `:asset-path "target"` in the cljs compiler options, but it has no effect, the resulting compiled js is the same.

I run all of this as a part of my `boot-clj`-based build and as far as I understand the current working directory is the one which is parent to the `target` directory and where the `build.boot` file is located. That explains why the `path.resolve(".")` call returns an incorrect value. 

From all this it seems it may be meaningful to add a `:working-directory` option to the `prerenderer.core/start!` method, which then would be propagated to a call to the `.directory(blahblah)` [method](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#directory%28java.io.File%29) on the `ProcessBuilder` instance.  

What do you guys think? Will you accept a pull request for this?

**Comment by pupeno** [comment]
I remember running into an issue similar to what you are describing, so I might have experienced this bug before but I just changed the structure of my project to work with the generated code. If you have a better solution, I'm all for getting the PR. :)

**Comment by eploko** [comment]
@pupeno no worries, you can check the PR out at #12 :)
